### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by bennage**
mostly to let people know that this is old

### CODE REVIEW

**Comment by bennage** [comment]
Sorry. I didn't realize I was on your fork! :stuck_out_tongue_winking_eye:

**Comment by nancymic2** [comment]
Hi Christopher,
Long time :)

I was really just playing around with git and thought I'd read as I worked on an
earlier version.
I didn't find many more pnp docs...
Nancy Michell

uoting Christopher Bennage notifications@github.com:

**Comment by bennage** [comment]
:wave: hi! I didn't realize this was you.If you have any git/markdown questions let me know.

**Comment by nancymic2** [comment]
Hey! sure thanks!!
How's it going there?

**Pull request closed without merging**
